### PR TITLE
refactor: splash screen

### PR DESCRIPTION
**Pull request by Barbapapazes**
### 🔗 Linked issue

This resolves a tweet from Romain: https://x.com/romainlanz/status/1833780808038912290

### ❓ Type of change

- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Screenshot 2024-09-11 at 17 46 58

*Please, read this to understand choices made in this PR:*

The splash screen page must be a standalone page. This means that it does not any external assets nor relying on external packages. This is to ensure that the developer creating a new project can remove the page with a single file to delete (or a `ctrl + a + delete` / `cmd + a + delete`).

Knowing this, all svg files are inlined in the page. In the same time, and because it's way faster to develop, I use the Tailwind CSS CDN to style the page. Since this page will not be used in production, it's not a problem. I also use a font CDN (Bunny) via a `link` tag in the `head` of the page.

The design of the page is inspired by the design of the home of Adonis (https://adonisjs.com). We can find the dotted lines, the colors (primary and sand), the font (Instrument) and the logo.

Cards are also inspired by cards available on the home of Adonis.

These choices are made to ensure a consistent design between the splash screen page and the home of Adonis. (I think it's important for the user experience).

For the features, I choose the following order:

- Lucid
- Vine
- Edge
- Japa

Because you need a database (lucid) that must be filled with verified and sanitized data (vine) then rendered in a view (edge). Finally, you need to test your application (japa).

If you have any questions, feel free to ask.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by RomainLanz** [comment]
LGTM!

Should we align the title with the small icons?

**Comment by Barbapapazes** [comment]
> LGTM!
> 
> Should we align the title with the small icons?

these ones?

Screenshot 2024-09-11 at 19 17 40

_I could have added too much margin top_

**Comment by RomainLanz** [comment]
Yes, they seem to be in the wrong place. We could move them to the same level as the title.

**Comment by RomainLanz** [comment]
I am not sure if we need any margin there, couldn't we just add padding to the card and make it a flex container?

Something like this https://github.com/RomainLanz/romainlanz.com/blob/main/packages/design-system/src/molecules/alert_note/alert_note.vue#L6

**Comment by Barbapapazes** [comment]
> I am not sure if we need any margin there, couldn't we just add padding to the card and make it a flex container?
> 
> Something like this https://github.com/RomainLanz/romainlanz.com/blob/main/packages/design-system/src/molecules/alert_note/alert_note.vue#L6

The paragraph is aligned (spaced) with the title not the icon. In order to use flex I'll need to create a container around the icon and the tittle and align the paragraph according to this block.

**Comment by RomainLanz** [comment]
Thanks! 🙌🏻

**Comment by thetutlage** [comment]
Guys, just triggered to me now. Should we create a layout component as well and use that? Because @RomainLanz many times people have asked us how to create layouts in Edge

**Comment by RomainLanz** [comment]
> Guys, just triggered to me now. Should we create a layout component as well and use that? Because @RomainLanz many times people have asked us how to create layouts in Edge

They asked because we removed the `@layout` feature without providing proper documentation at first. Now that we've added it, I haven't seen any more questions related to Layouts and Edge.

So, I suggest we keep the starting page as it is to avoid clutter and make it easy to remove later.

**Comment by thetutlage** [comment]
Cool

**Pull request merged**
